let x = '';
x = ' '.repeat(4)+'*';
console.log(x);
x = ' '.repeat(3)+'*'.repeat(2);
console.log(x);
x = ' '.repeat(2)+'*'.repeat(3);
console.log(x);
x = ' '.repeat(1)+'*'.repeat(4);
console.log(x);
x = '*'.repeat(5);
console.log(x);
